### ISSUE TITLE
"Please login"  button text is not on the box

### ISSUE THREAD

**Issue by pontakornth** [Ing140943/anicheck#53]
It is in the homepage. If the mouse is not hovered on the button, it won't highlight.

<img width="251" alt="Screen Shot 2564-11-22 at 11 13 39" src="https://user-images.githubusercontent.com/37771900/142800333-8526bfd7-0d9f-4c9e-a169-3442aa9a6b25.png">

It also overlap with the search bar.

**Comment by Ing140943** [comment]
Thank you for your reporting. The new user interface will deploy soon in 1-2 days. Please come back and check it again. Thank you.
