### ISSUE TITLE
Forget to turn off DEBUG=True on production

### ISSUE THREAD

**Issue by pontakornth** [Ing140943/anicheck#54]
# Step to reproduce
1. Go to https://anicheck-isp.herokuapp.com/russia
2. You should see Django 404 page.

# Screenshot
I stripped the routes.
<img width="1440" alt="Anicheck Strip" src="https://user-images.githubusercontent.com/37771900/142800881-0c3d5c55-9d3e-4e43-ac96-a07f3bf13c16.png">

**Comment by boom210232** [comment]
@pontakornth Yes It a problem for now because we can't deploy without this for some reason in heroku.
If you have any idea that useful for us it will be great. 
Have a good day P.

**Comment by Ing140943** [comment]
Actually, we ask TA about this already. Our web application has some modules that we need to make the DEBUG is True to make can execute while we deploy. The module that is required for DEBUG is True is kitsu.
