### ISSUE TITLE
Cannot use MyList button

### ISSUE THREAD

**Issue by HuskyIsHere** [Ing140943/anicheck#56]
The MyList button on the navigation bar doesn't do anything.

![Untitled](https://user-images.githubusercontent.com/72660373/142808865-67facb2d-fbff-424c-904e-e67c0cfa425e.png)

**Comment by boom210232** [comment]
@HuskyIsHere Sorry for any inconvenience. This task is delay because my personal reason (This task assignees is me.) It maybe deploy fastest on Wednesday. 

https://www.youtube.com/watch?v=ih9zBLDr_ro -> Not rickroll trust me! (For relaxing.)
