### ISSUE TITLE
[BUG] typing a long message in search box it raise error 500.

### ISSUE THREAD

**Issue by vitvara** [Ing140943/anicheck#61]
## IMG BUG
<img width="1492" alt="image" src="https://user-images.githubusercontent.com/69972884/143398913-286b6db8-578d-42b5-a578-8e1a370a5dc3.png">
<img width="423" alt="image" src="https://user-images.githubusercontent.com/69972884/143399188-35f31ada-8c0b-4ccf-a79e-7c4f403a5e4e.png">

## Step to reproduce
In home page
at search box typing
`หกดฟฟหกฟหกด้่าสฟหกดฟหกด้่ฟหกดหกดฟเสฟหกดด่าสฟหเด่าๆห้ฤษศฏโฌ็ฤษศห่กดเ้๋ษศฤซฆฏ็ษศฟ่ห้กาสฤ็โษศฆ๋ฤฏฌฺโ๋ษศฤฆฏฌฏโ๋ษศฟห้กส่าฤ็ฆษศฏฒฬ`

**Comment by Ing140943** [comment]
Oh, we will handle this problem in our refactoring. Thank you so much.
