### ISSUE TITLE
Anime items doesn't navigate to details.

### ISSUE THREAD

**Issue by tboonma** [Ing140943/anicheck#62]
## Step to reproduce

Go to [https://anicheck-isp.herokuapp.com/](https://anicheck-isp.herokuapp.com/)
click on any anime listed here
<img width="1551" alt="Screen Shot 2564-11-25 at 14 32 43" src="https://user-images.githubusercontent.com/63687258/143398599-56c54246-6891-4f75-80d6-09d2b97a4cfc.png">

## Expected result
Should go to detail page?

## Actual result
Nothing happen.

**Comment by Ing140943** [comment]
Yes, we will implement it. You can try it when we complete all features on our web application(In 2-3 days). Thanks.
